# Generated by Django 3.0.5 on 2020-05-05 00:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_hamburgesa_precio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hamburgesa',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='ingrediente',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='hamburgesa',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
