# Generated by Django 3.0.5 on 2020-05-05 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0003_auto_20200504_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hamburgesa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ingrediente',
            options={},
        ),
        migrations.RemoveField(
            model_name='hamburgesa',
            name='created',
        ),
    ]
