# Generated by Django 3.0.5 on 2020-05-05 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0004_auto_20200504_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='created',
        ),
    ]
